/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Region */

#ifndef _Included_bwapi_Region
#define _Included_bwapi_Region
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Region
 * Method:    getID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Region_getID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    getRegionGroupID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Region_getRegionGroupID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    getCenter_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Region_getCenter_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    isHigherGround_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Region_isHigherGround_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    getDefensePriority_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Region_getDefensePriority_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    isWalkable_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Region_isWalkable_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    getBoundsLeft_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Region_getBoundsLeft_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    getBoundsTop_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Region_getBoundsTop_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    getBoundsRight_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Region_getBoundsRight_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    getBoundsBottom_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Region_getBoundsBottom_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    getClosestAccessibleRegion_native
 * Signature: (J)Lbwapi/Region;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Region_getClosestAccessibleRegion_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    getClosestInaccessibleRegion_native
 * Signature: (J)Lbwapi/Region;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Region_getClosestInaccessibleRegion_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Region
 * Method:    getDistance_native
 * Signature: (JLbwapi/Region;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Region_getDistance_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
