/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_PlayerImpl */

#ifndef _Included_bwapi_PlayerImpl
#define _Included_bwapi_PlayerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_PlayerImpl
 * Method:    clear_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi_PlayerImpl_clear_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_getID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getName_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi_PlayerImpl_getName_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getUnits_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_PlayerImpl_getUnits_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getRace_native
 * Signature: (J)Lbwapi/Race;
 */
JNIEXPORT jobject JNICALL Java_bwapi_PlayerImpl_getRace_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getType_native
 * Signature: (J)Lbwapi/PlayerType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_PlayerImpl_getType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getForce_native
 * Signature: (J)Lbwapi/Force;
 */
JNIEXPORT jobject JNICALL Java_bwapi_PlayerImpl_getForce_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    isAlly_native
 * Signature: (JLbwapi/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_isAlly_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    isEnemy_native
 * Signature: (JLbwapi/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_isEnemy_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    isNeutral_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_isNeutral_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getStartLocation_native
 * Signature: (J)Lbwapi/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi_PlayerImpl_getStartLocation_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    isVictorious_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_isVictorious_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    isDefeated_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_isDefeated_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    leftGame_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_leftGame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    minerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_minerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    gas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_gas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    gatheredMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_gatheredMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    gatheredGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_gatheredGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    repairedMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_repairedMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    repairedGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_repairedGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    refundedMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_refundedMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    refundedGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_refundedGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    spentMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_spentMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    spentGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_spentGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    supplyTotal_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_supplyTotal_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    supplyUsed_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_supplyUsed_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    supplyTotal_native
 * Signature: (JLbwapi/Race;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_supplyTotal_1native__JLbwapi_Race_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    supplyUsed_native
 * Signature: (JLbwapi/Race;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_supplyUsed_1native__JLbwapi_Race_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    allUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_allUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    visibleUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_visibleUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    completedUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_completedUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    incompleteUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_incompleteUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    deadUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_deadUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    killedUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_killedUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    hasResearched_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_hasResearched_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    isResearching_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_isResearching_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    isUpgrading_native
 * Signature: (JLbwapi/UpgradeType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_isUpgrading_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getTextColor_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_getTextColor_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    maxEnergy_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_maxEnergy_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    topSpeed_native
 * Signature: (JLbwapi/UnitType;)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_PlayerImpl_topSpeed_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    groundWeaponMaxRange_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_groundWeaponMaxRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    airWeaponMaxRange_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_airWeaponMaxRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    weaponMaxRange_native
 * Signature: (JLbwapi/WeaponType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_weaponMaxRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    sightRange_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_sightRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    groundWeaponDamageCooldown_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_groundWeaponDamageCooldown_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    armor_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_armor_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getUnitScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_getUnitScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getKillScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_getKillScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getBuildingScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_getBuildingScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getRazingScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_getRazingScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    getCustomScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_PlayerImpl_getCustomScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    isObserver_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_isObserver_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    isResearchAvailable_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_isResearchAvailable_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_PlayerImpl
 * Method:    isUnitAvailable_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerImpl_isUnitAvailable_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
