/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_PositionOrUnit */

#ifndef _Included_bwapi_PositionOrUnit
#define _Included_bwapi_PositionOrUnit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_PositionOrUnit
 * Method:    isUnit_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PositionOrUnit_isUnit_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PositionOrUnit
 * Method:    getUnit_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_PositionOrUnit_getUnit_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PositionOrUnit
 * Method:    isPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PositionOrUnit_isPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PositionOrUnit
 * Method:    getPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_PositionOrUnit_getPosition_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
