/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Error */

#ifndef _Included_bwapi_Error
#define _Included_bwapi_Error
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Error
 * Method:    c_str_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi_Error_c_1str_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
