/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_PositionedObject */

#ifndef _Included_bwapi_PositionedObject
#define _Included_bwapi_PositionedObject
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
