/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi__MouseButton */

#ifndef _Included_bwapi__MouseButton
#define _Included_bwapi__MouseButton
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
