/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_RegionImpl */

#ifndef _Included_bwapi_RegionImpl
#define _Included_bwapi_RegionImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_RegionImpl
 * Method:    setNeighbors_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi_RegionImpl_setNeighbors_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_RegionImpl
 * Method:    getID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_RegionImpl_getID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_RegionImpl
 * Method:    getRegionGroupID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_RegionImpl_getRegionGroupID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_RegionImpl
 * Method:    isHigherGround_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_RegionImpl_isHigherGround_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_RegionImpl
 * Method:    getDefensePriority_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_RegionImpl_getDefensePriority_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_RegionImpl
 * Method:    isWalkable_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_RegionImpl_isWalkable_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_RegionImpl
 * Method:    getBoundsLeft_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_RegionImpl_getBoundsLeft_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_RegionImpl
 * Method:    getBoundsTop_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_RegionImpl_getBoundsTop_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_RegionImpl
 * Method:    getBoundsRight_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_RegionImpl_getBoundsRight_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_RegionImpl
 * Method:    getBoundsBottom_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_RegionImpl_getBoundsBottom_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_RegionImpl
 * Method:    getDistance_native
 * Signature: (JLbwapi/Region;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_RegionImpl_getDistance_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
