/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_UnaryFilter */

#ifndef _Included_bwapi4_UnaryFilter
#define _Included_bwapi4_UnaryFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
