/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_GameWrapper */

#ifndef _Included_bwapi_GameWrapper
#define _Included_bwapi_GameWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_GameWrapper
 * Method:    flush_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi_GameWrapper_flush_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
