/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_UnitImpl */

#ifndef _Included_bwapi_UnitImpl
#define _Included_bwapi_UnitImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_UnitImpl
 * Method:    clear_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi_UnitImpl_clear_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    saveInitialState_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi_UnitImpl_saveInitialState_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getTilePosition_native
 * Signature: (J)Lbwapi/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi_UnitImpl_getTilePosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getInitialTilePosition_native
 * Signature: (J)Lbwapi/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi_UnitImpl_getInitialTilePosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getKillCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getKillCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getAcidSporeCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getAcidSporeCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getInterceptorCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getInterceptorCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getScarabCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getScarabCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getSpiderMineCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getSpiderMineCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getGroundWeaponCooldown_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getGroundWeaponCooldown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getAirWeaponCooldown_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getAirWeaponCooldown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getSpellCooldown_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getSpellCooldown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getDefenseMatrixPoints_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getDefenseMatrixPoints_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getDefenseMatrixTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getDefenseMatrixTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getEnsnareTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getEnsnareTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getIrradiateTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getIrradiateTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getLockdownTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getLockdownTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getMaelstromTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getMaelstromTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getOrderTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getOrderTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getPlagueTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getPlagueTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getRemoveTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getRemoveTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getStasisTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getStasisTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getStimTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_UnitImpl_getStimTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getTargetPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_UnitImpl_getTargetPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getOrderTargetPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_UnitImpl_getOrderTargetPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getRallyPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_UnitImpl_getRallyPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getLoadedUnits_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_UnitImpl_getLoadedUnits_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getInterceptors_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_UnitImpl_getInterceptors_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getLarva_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_UnitImpl_getLarva_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getUnitsInRadius_native
 * Signature: (JI)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_UnitImpl_getUnitsInRadius_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getUnitsInWeaponRange_native
 * Signature: (JLbwapi/WeaponType;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_UnitImpl_getUnitsInWeaponRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    getClientInfo_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi_UnitImpl_getClientInfo_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    exists_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_exists_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    hasNuke_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_hasNuke_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isAccelerating_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isAccelerating_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isAttackFrame_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isAttackFrame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isAttacking_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isAttacking_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isBeingConstructed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isBeingConstructed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isBeingGathered_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isBeingGathered_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isBeingHealed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isBeingHealed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isBlind_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isBlind_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isBraking_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isBraking_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isBurrowed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isBurrowed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isCarryingGas_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isCarryingGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isCarryingMinerals_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isCarryingMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isCloaked_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isCloaked_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isCompleted_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isCompleted_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isConstructing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isConstructing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isDefenseMatrixed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isDefenseMatrixed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isDetected_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isDetected_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isEnsnared_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isEnsnared_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isFollowing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isFollowing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isGatheringGas_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isGatheringGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isGatheringMinerals_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isGatheringMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isHallucination_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isHallucination_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isHoldingPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isHoldingPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isIdle_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isIdle_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isInWeaponRange_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isInWeaponRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isInterruptible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isInterruptible_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isInvincible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isInvincible_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isIrradiated_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isIrradiated_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isLifted_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isLifted_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isLoaded_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isLoaded_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isLockedDown_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isLockedDown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isMaelstrommed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isMaelstrommed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isMorphing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isMorphing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isMoving_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isMoving_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isParasited_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isParasited_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isPatrolling_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isPatrolling_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isPlagued_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isPlagued_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isRepairing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isRepairing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isResearching_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isResearching_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isSelected_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isSelected_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isSieged_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isSieged_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isStartingAttack_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isStartingAttack_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isStasised_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isStasised_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isStimmed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isStimmed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isStuck_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isStuck_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isTraining_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isTraining_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isUnderAttack_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isUnderAttack_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isUnderDarkSwarm_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isUnderDarkSwarm_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isUnderDisruptionWeb_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isUnderDisruptionWeb_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isUnderStorm_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isUnderStorm_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isUnpowered_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isUnpowered_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isUpgrading_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isUpgrading_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isVisible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isVisible_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    isVisible_native
 * Signature: (JLbwapi/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_isVisible_1native__JLbwapi_Player_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    canIssueCommand_native
 * Signature: (JLbwapi/UnitCommand;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_canIssueCommand_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    issueCommand_native
 * Signature: (JLbwapi/UnitCommand;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_issueCommand_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    attack_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_attack_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    attack_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_attack_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    build_native
 * Signature: (JLbwapi/TilePosition;Lbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_build_1native
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    buildAddon_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_buildAddon_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    train_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_train_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    morph_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_morph_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    research_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_research_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    upgrade_native
 * Signature: (JLbwapi/UpgradeType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_upgrade_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    setRallyPoint_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_setRallyPoint_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    setRallyPoint_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_setRallyPoint_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    move_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_move_1native
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    patrol_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_patrol_1native
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    holdPosition_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_holdPosition_1native
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    stop_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_stop_1native
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    follow_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_follow_1native
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    gather_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_gather_1native
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    returnCargo_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_returnCargo_1native
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    repair_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_repair_1native
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    burrow_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_burrow_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    unburrow_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_unburrow_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    cloak_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_cloak_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    decloak_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_decloak_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    siege_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_siege_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    unsiege_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_unsiege_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    lift_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_lift_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    land_native
 * Signature: (JLbwapi/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_land_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    load_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_load_1native
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    unload_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_unload_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    unloadAll_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_unloadAll_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    unloadAll_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_unloadAll_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    rightClick_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_rightClick_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    rightClick_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_rightClick_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_UnitImpl
 * Method:    haltConstruction_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_haltConstruction_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    cancelConstruction_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_cancelConstruction_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    cancelAddon_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_cancelAddon_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    cancelTrain_native
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_cancelTrain_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi_UnitImpl
 * Method:    cancelMorph_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_cancelMorph_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    cancelResearch_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_cancelResearch_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    cancelUpgrade_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_cancelUpgrade_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_UnitImpl
 * Method:    useTech_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_useTech_1native__JLbwapi_TechType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    useTech_native
 * Signature: (JLbwapi/TechType;Lbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_useTech_1native__JLbwapi_TechType_2Lbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    useTech_native
 * Signature: (JLbwapi/TechType;Lbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_useTech_1native__JLbwapi_TechType_2Lbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_UnitImpl
 * Method:    placeCOP_native
 * Signature: (JLbwapi/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_UnitImpl_placeCOP_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
