/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_UnitCommand */

#ifndef _Included_bwapi4_UnitCommand
#define _Included_bwapi4_UnitCommand
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_UnitCommand
 * Method:    getType_native
 * Signature: (J)Lbwapi4/UnitCommandType;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_UnitCommand_getType_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
