/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Color */

#ifndef _Included_bwapi4_Color
#define _Included_bwapi4_Color
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_Color
 * Method:    red_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Color_red_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Color
 * Method:    green_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Color_green_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Color
 * Method:    blue_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Color_blue_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
