/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Tournament_ActionID */

#ifndef _Included_bwapi_Tournament_ActionID
#define _Included_bwapi_Tournament_ActionID
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
