/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Unit */

#ifndef _Included_bwapi_Unit
#define _Included_bwapi_Unit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Unit
 * Method:    getID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getReplayID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getReplayID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getPlayer_native
 * Signature: (J)Lbwapi/Player;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getPlayer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getType_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTilePosition_native
 * Signature: (J)Lbwapi/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getTilePosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getAngle_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Unit_getAngle_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getVelocityX_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Unit_getVelocityX_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getVelocityY_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Unit_getVelocityY_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRegion_native
 * Signature: (J)Lbwapi/Region;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getRegion_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLeft_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getLeft_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTop_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getTop_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRight_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRight_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getBottom_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getBottom_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getHitPoints_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getHitPoints_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getShields_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getShields_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getEnergy_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getEnergy_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getResources_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getResources_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getResourceGroup_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getResourceGroup_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getDistance_native
 * Signature: (JLbwapi/Unit;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getDistance_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    getDistance_native
 * Signature: (JLbwapi/Position;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getDistance_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    hasPath_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_hasPath_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    hasPath_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_hasPath_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    getLastCommandFrame_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getLastCommandFrame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLastAttackingPlayer_native
 * Signature: (J)Lbwapi/Player;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getLastAttackingPlayer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getUpgradeLevel_native
 * Signature: (JLbwapi/UpgradeType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getUpgradeLevel_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    getInitialType_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getInitialType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInitialPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getInitialPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInitialTilePosition_native
 * Signature: (J)Lbwapi/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getInitialTilePosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInitialHitPoints_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getInitialHitPoints_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInitialResources_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getInitialResources_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getKillCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getKillCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getAcidSporeCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getAcidSporeCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInterceptorCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getInterceptorCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getScarabCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getScarabCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getSpiderMineCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getSpiderMineCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getGroundWeaponCooldown_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getGroundWeaponCooldown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getAirWeaponCooldown_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getAirWeaponCooldown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getSpellCooldown_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getSpellCooldown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getDefenseMatrixPoints_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getDefenseMatrixPoints_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getDefenseMatrixTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getDefenseMatrixTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getEnsnareTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getEnsnareTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getIrradiateTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getIrradiateTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLockdownTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getLockdownTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getMaelstromTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getMaelstromTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getOrderTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getOrderTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getPlagueTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getPlagueTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRemoveTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRemoveTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getStasisTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getStasisTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getStimTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getStimTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getBuildType_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getBuildType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTech_native
 * Signature: (J)Lbwapi/TechType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getTech_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getUpgrade_native
 * Signature: (J)Lbwapi/UpgradeType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getUpgrade_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRemainingBuildTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRemainingBuildTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRemainingTrainTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRemainingTrainTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRemainingResearchTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRemainingResearchTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRemainingUpgradeTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRemainingUpgradeTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getBuildUnit_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getBuildUnit_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTarget_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getTarget_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTargetPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getTargetPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getOrder_native
 * Signature: (J)Lbwapi/Order;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getOrder_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getSecondaryOrder_native
 * Signature: (J)Lbwapi/Order;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getSecondaryOrder_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getOrderTarget_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getOrderTarget_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getOrderTargetPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getOrderTargetPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRallyPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getRallyPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRallyUnit_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getRallyUnit_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getAddon_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getAddon_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getNydusExit_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getNydusExit_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getPowerUp_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getPowerUp_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTransport_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getTransport_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLoadedUnits_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getLoadedUnits_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getCarrier_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getCarrier_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInterceptors_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getInterceptors_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getHatchery_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getHatchery_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLarva_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getLarva_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getUnitsInRadius_native
 * Signature: (JI)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getUnitsInRadius_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi_Unit
 * Method:    getUnitsInWeaponRange_native
 * Signature: (JLbwapi/WeaponType;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getUnitsInWeaponRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    exists_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_exists_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    hasNuke_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_hasNuke_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isAccelerating_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isAccelerating_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isAttacking_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isAttacking_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isAttackFrame_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isAttackFrame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBeingConstructed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBeingConstructed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBeingGathered_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBeingGathered_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBeingHealed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBeingHealed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBlind_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBlind_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBraking_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBraking_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBurrowed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBurrowed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isCarryingGas_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isCarryingGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isCarryingMinerals_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isCarryingMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isCloaked_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isCloaked_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isCompleted_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isCompleted_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isConstructing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isConstructing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isDefenseMatrixed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isDefenseMatrixed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isDetected_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isDetected_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isEnsnared_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isEnsnared_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isFollowing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isFollowing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isGatheringGas_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isGatheringGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isGatheringMinerals_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isGatheringMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isHallucination_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isHallucination_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isHoldingPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isHoldingPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isIdle_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isIdle_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isInterruptible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isInterruptible_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isInvincible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isInvincible_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isInWeaponRange_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isInWeaponRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    isIrradiated_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isIrradiated_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isLifted_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isLifted_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isLoaded_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isLoaded_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isLockedDown_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isLockedDown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isMaelstrommed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isMaelstrommed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isMorphing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isMorphing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isMoving_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isMoving_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isParasited_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isParasited_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isPatrolling_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isPatrolling_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isPlagued_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isPlagued_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isRepairing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isRepairing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isResearching_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isResearching_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isSelected_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isSelected_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isSieged_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isSieged_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isStartingAttack_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isStartingAttack_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isStasised_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isStasised_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isStimmed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isStimmed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isStuck_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isStuck_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isTraining_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isTraining_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUnderAttack_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUnderAttack_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUnderDarkSwarm_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUnderDarkSwarm_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUnderDisruptionWeb_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUnderDisruptionWeb_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUnderStorm_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUnderStorm_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUnpowered_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUnpowered_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUpgrading_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUpgrading_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isVisible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isVisible_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isVisible_native
 * Signature: (JLbwapi/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isVisible_1native__JLbwapi_Player_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommand_native
 * Signature: (JLbwapi/UnitCommand;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommand_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    issueCommand_native
 * Signature: (JLbwapi/UnitCommand;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_issueCommand_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    attack_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_attack_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    attack_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_attack_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    attack_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_attack_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    attack_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_attack_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    build_native
 * Signature: (JLbwapi/TilePosition;Lbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_build_1native
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    buildAddon_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_buildAddon_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    train_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_train_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    morph_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_morph_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    research_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_research_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    upgrade_native
 * Signature: (JLbwapi/UpgradeType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_upgrade_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    setRallyPoint_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_setRallyPoint_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    setRallyPoint_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_setRallyPoint_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    move_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_move_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    move_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_move_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    patrol_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_patrol_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    patrol_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_patrol_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    holdPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_holdPosition_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    holdPosition_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_holdPosition_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    stop_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_stop_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    stop_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_stop_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    follow_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_follow_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    follow_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_follow_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    gather_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_gather_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    gather_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_gather_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    returnCargo_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_returnCargo_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    returnCargo_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_returnCargo_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    repair_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_repair_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    repair_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_repair_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    burrow_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_burrow_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    unburrow_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unburrow_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cloak_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cloak_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    decloak_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_decloak_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    siege_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_siege_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    unsiege_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unsiege_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    lift_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_lift_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    land_native
 * Signature: (JLbwapi/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_land_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    load_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_load_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    load_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_load_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    unload_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unload_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    unloadAll_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unloadAll_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    unloadAll_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unloadAll_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    unloadAll_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unloadAll_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    unloadAll_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unloadAll_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    rightClick_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_rightClick_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    rightClick_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_rightClick_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    rightClick_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_rightClick_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    rightClick_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_rightClick_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    haltConstruction_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_haltConstruction_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelConstruction_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelConstruction_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelAddon_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelAddon_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelTrain_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelTrain_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelTrain_native
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelTrain_1native__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi_Unit
 * Method:    cancelMorph_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelMorph_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelResearch_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelResearch_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelUpgrade_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelUpgrade_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    useTech_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_useTech_1native__JLbwapi_TechType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    useTech_native
 * Signature: (JLbwapi/TechType;Lbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_useTech_1native__JLbwapi_TechType_2Lbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    useTech_native
 * Signature: (JLbwapi/TechType;Lbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_useTech_1native__JLbwapi_TechType_2Lbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    placeCOP_native
 * Signature: (JLbwapi/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_placeCOP_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
