/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_UnitType */

#ifndef _Included_bwapi4_UnitType
#define _Included_bwapi4_UnitType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
