/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_CenteredObject */

#ifndef _Included_bwapi_CenteredObject
#define _Included_bwapi_CenteredObject
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
