/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_GameWrapper */

#ifndef _Included_bwapi4_GameWrapper
#define _Included_bwapi4_GameWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_GameWrapper
 * Method:    flush_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi4_GameWrapper_flush_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
