/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_BWAPI_MouseButton */

#ifndef _Included_bwapi_BWAPI_MouseButton
#define _Included_bwapi_BWAPI_MouseButton
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
