/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Order */

#ifndef _Included_bwapi_Order
#define _Included_bwapi_Order
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Order
 * Method:    c_str_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi_Order_c_1str_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
