/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_BestUnitFilter */

#ifndef _Included_bwapi_BestUnitFilter
#define _Included_bwapi_BestUnitFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
