/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_TournamentModule */

#ifndef _Included_bwapi_TournamentModule
#define _Included_bwapi_TournamentModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_TournamentModule
 * Method:    onFirstAdvertisement_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi_TournamentModule_onFirstAdvertisement_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
