/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_AbstractPoint */

#ifndef _Included_bwapi_AbstractPoint
#define _Included_bwapi_AbstractPoint
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
