/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Point */

#ifndef _Included_bwapi_Point
#define _Included_bwapi_Point
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Point
 * Method:    isValid_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Point_isValid_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Point
 * Method:    getDistance_native
 * Signature: (JLbwapi/Point;)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Point_getDistance_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Point
 * Method:    getLength_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Point_getLength_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Point
 * Method:    getApproxDistance_native
 * Signature: (JLbwapi/Point;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Point_getApproxDistance_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
