/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Force */

#ifndef _Included_bwapi_Force
#define _Included_bwapi_Force
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Force
 * Method:    getID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Force_getID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Force
 * Method:    getName_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi_Force_getName_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Force
 * Method:    getPlayers_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Force_getPlayers_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
