/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Forceset */

#ifndef _Included_bwapi4_Forceset
#define _Included_bwapi4_Forceset
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_Forceset
 * Method:    getPlayers_native
 * Signature: (J)Lbwapi4/Playerset;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Forceset_getPlayers_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
