/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Playerset */

#ifndef _Included_bwapi_Playerset
#define _Included_bwapi_Playerset
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Playerset
 * Method:    getUnits_native
 * Signature: (J)Lbwapi/Unitset;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Playerset_getUnits_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Playerset
 * Method:    setAlliance_native
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_bwapi_Playerset_setAlliance_1native
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
