/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_BWEventListener */

#ifndef _Included_bwapi_BWEventListener
#define _Included_bwapi_BWEventListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
