/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Player */

#ifndef _Included_bwapi_Player
#define _Included_bwapi_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Player
 * Method:    getID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_getID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getName_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi_Player_getName_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getUnits_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Player_getUnits_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getRace_native
 * Signature: (J)Lbwapi/Race;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Player_getRace_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getType_native
 * Signature: (J)Lbwapi/PlayerType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Player_getType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getForce_native
 * Signature: (J)Lbwapi/Force;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Player_getForce_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    isAlly_native
 * Signature: (JLbwapi/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_isAlly_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    isEnemy_native
 * Signature: (JLbwapi/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_isEnemy_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    isNeutral_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_isNeutral_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getStartLocation_native
 * Signature: (J)Lbwapi/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Player_getStartLocation_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    isVictorious_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_isVictorious_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    isDefeated_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_isDefeated_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    leftGame_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_leftGame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    minerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_minerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    gas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_gas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    gatheredMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_gatheredMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    gatheredGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_gatheredGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    repairedMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_repairedMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    repairedGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_repairedGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    refundedMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_refundedMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    refundedGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_refundedGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    spentMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_spentMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    spentGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_spentGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    supplyTotal_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_supplyTotal_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    supplyTotal_native
 * Signature: (JLbwapi/Race;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_supplyTotal_1native__JLbwapi_Race_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    supplyUsed_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_supplyUsed_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    supplyUsed_native
 * Signature: (JLbwapi/Race;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_supplyUsed_1native__JLbwapi_Race_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    allUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_allUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    visibleUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_visibleUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    completedUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_completedUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    incompleteUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_incompleteUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    deadUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_deadUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    killedUnitCount_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_killedUnitCount_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    hasResearched_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_hasResearched_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    isResearching_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_isResearching_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    isUpgrading_native
 * Signature: (JLbwapi/UpgradeType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_isUpgrading_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    getColor_native
 * Signature: (J)Lbwapi/Color;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Player_getColor_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getTextColor_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_getTextColor_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    maxEnergy_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_maxEnergy_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    topSpeed_native
 * Signature: (JLbwapi/UnitType;)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Player_topSpeed_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    groundWeaponMaxRange_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_groundWeaponMaxRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    airWeaponMaxRange_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_airWeaponMaxRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    weaponMaxRange_native
 * Signature: (JLbwapi/WeaponType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_weaponMaxRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    sightRange_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_sightRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    groundWeaponDamageCooldown_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_groundWeaponDamageCooldown_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    armor_native
 * Signature: (JLbwapi/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_armor_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    getUnitScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_getUnitScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getKillScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_getKillScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getBuildingScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_getBuildingScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getRazingScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_getRazingScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    getCustomScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Player_getCustomScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    isObserver_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_isObserver_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Player
 * Method:    isResearchAvailable_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_isResearchAvailable_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Player
 * Method:    isUnitAvailable_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Player_isUnitAvailable_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
