/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Position */

#ifndef _Included_bwapi4_Position
#define _Included_bwapi4_Position
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_Position
 * Method:    isValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Position_isValid
  (JNIEnv *, jobject);

/*
 * Class:     bwapi4_Position
 * Method:    makeValid
 * Signature: ()Lbwapi4/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Position_makeValid
  (JNIEnv *, jobject);

/*
 * Class:     bwapi4_Position
 * Method:    getDistance
 * Signature: (Lbwapi4/Position;)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi4_Position_getDistance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bwapi4_Position
 * Method:    getApproxDistance
 * Signature: (Lbwapi4/Position;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Position_getApproxDistance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bwapi4_Position
 * Method:    getLength
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_bwapi4_Position_getLength
  (JNIEnv *, jobject);

/*
 * Class:     bwapi4_Position
 * Method:    hasPath
 * Signature: (Lbwapi4/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Position_hasPath
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
