/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwta_BaseLocation */

#ifndef _Included_bwta_BaseLocation
#define _Included_bwta_BaseLocation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwta_BaseLocation
 * Method:    getPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwta_BaseLocation_getPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_BaseLocation
 * Method:    getTilePosition_native
 * Signature: (J)Lbwapi/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwta_BaseLocation_getTilePosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_BaseLocation
 * Method:    getRegion_native
 * Signature: (J)Lbwta/Region;
 */
JNIEXPORT jobject JNICALL Java_bwta_BaseLocation_getRegion_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_BaseLocation
 * Method:    minerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwta_BaseLocation_minerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_BaseLocation
 * Method:    gas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwta_BaseLocation_gas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_BaseLocation
 * Method:    getGroundDistance_native
 * Signature: (JLbwta/BaseLocation;)D
 */
JNIEXPORT jdouble JNICALL Java_bwta_BaseLocation_getGroundDistance_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwta_BaseLocation
 * Method:    getAirDistance_native
 * Signature: (JLbwta/BaseLocation;)D
 */
JNIEXPORT jdouble JNICALL Java_bwta_BaseLocation_getAirDistance_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwta_BaseLocation
 * Method:    isIsland_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwta_BaseLocation_isIsland_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_BaseLocation
 * Method:    isMineralOnly_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwta_BaseLocation_isMineralOnly_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_BaseLocation
 * Method:    isStartLocation_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwta_BaseLocation_isStartLocation_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
