/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwta_Region */

#ifndef _Included_bwta_Region
#define _Included_bwta_Region
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwta_Region
 * Method:    getPolygon_native
 * Signature: (J)Lbwta/Polygon;
 */
JNIEXPORT jobject JNICALL Java_bwta_Region_getPolygon_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Region
 * Method:    getCenter_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwta_Region_getCenter_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Region
 * Method:    getChokepoints_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwta_Region_getChokepoints_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Region
 * Method:    getBaseLocations_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwta_Region_getBaseLocations_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Region
 * Method:    isReachable_native
 * Signature: (JLbwta/Region;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwta_Region_isReachable_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwta_Region
 * Method:    getReachableRegions_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwta_Region_getReachableRegions_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
