/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_WeaponType */

#ifndef _Included_bwapi4_WeaponType
#define _Included_bwapi4_WeaponType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_WeaponType
 * Method:    toString_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi4_WeaponType_toString_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    getTech_native
 * Signature: (J)Lbwapi4/TechType;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_WeaponType_getTech_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    whatUses_native
 * Signature: (J)Lbwapi4/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_WeaponType_whatUses_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    damageAmount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_WeaponType_damageAmount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    damageBonus_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_WeaponType_damageBonus_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    damageCooldown_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_WeaponType_damageCooldown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    damageFactor_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_WeaponType_damageFactor_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    upgradeType_native
 * Signature: (J)Lbwapi4/UpgradeType;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_WeaponType_upgradeType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    damageType_native
 * Signature: (J)Lbwapi4/DamageType;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_WeaponType_damageType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    explosionType_native
 * Signature: (J)Lbwapi4/ExplosionType;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_WeaponType_explosionType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    minRange_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_WeaponType_minRange_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    maxRange_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_WeaponType_maxRange_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    innerSplashRadius_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_WeaponType_innerSplashRadius_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    medianSplashRadius_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_WeaponType_medianSplashRadius_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    outerSplashRadius_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_WeaponType_outerSplashRadius_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    targetsAir_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_WeaponType_targetsAir_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    targetsGround_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_WeaponType_targetsGround_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    targetsMechanical_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_WeaponType_targetsMechanical_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    targetsOrganic_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_WeaponType_targetsOrganic_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    targetsNonBuilding_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_WeaponType_targetsNonBuilding_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    targetsNonRobotic_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_WeaponType_targetsNonRobotic_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    targetsTerrain_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_WeaponType_targetsTerrain_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    targetsOrgOrMech_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_WeaponType_targetsOrgOrMech_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_WeaponType
 * Method:    targetsOwn_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_WeaponType_targetsOwn_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
