/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Player */

#ifndef _Included_bwapi4_Player
#define _Included_bwapi4_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_Player
 * Method:    getID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_getID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getName_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi4_Player_getName_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getRace_native
 * Signature: (J)Lbwapi4/Race;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Player_getRace_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getType_native
 * Signature: (J)Lbwapi4/PlayerType;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Player_getType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getForce_native
 * Signature: (J)Lbwapi4/Force;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Player_getForce_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    isAlly_native
 * Signature: (JLbwapi4/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_isAlly_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    isEnemy_native
 * Signature: (JLbwapi4/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_isEnemy_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    isNeutral_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_isNeutral_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getStartLocation_native
 * Signature: (J)Lbwapi4/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Player_getStartLocation_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    isVictorious_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_isVictorious_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    isDefeated_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_isDefeated_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    leftGame_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_leftGame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    minerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_minerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    gas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_gas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    gatheredMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_gatheredMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    gatheredGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_gatheredGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    repairedMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_repairedMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    repairedGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_repairedGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    refundedMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_refundedMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    refundedGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_refundedGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    spentMinerals_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_spentMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    spentGas_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_spentGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    supplyTotal_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_supplyTotal_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    supplyTotal_native
 * Signature: (JLbwapi4/Race;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_supplyTotal_1native__JLbwapi4_Race_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    supplyUsed_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_supplyUsed_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    supplyUsed_native
 * Signature: (JLbwapi4/Race;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_supplyUsed_1native__JLbwapi4_Race_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    allUnitCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_allUnitCount_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    allUnitCount_native
 * Signature: (JLbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_allUnitCount_1native__JLbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    visibleUnitCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_visibleUnitCount_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    visibleUnitCount_native
 * Signature: (JLbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_visibleUnitCount_1native__JLbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    completedUnitCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_completedUnitCount_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    completedUnitCount_native
 * Signature: (JLbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_completedUnitCount_1native__JLbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    incompleteUnitCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_incompleteUnitCount_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    incompleteUnitCount_native
 * Signature: (JLbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_incompleteUnitCount_1native__JLbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    deadUnitCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_deadUnitCount_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    deadUnitCount_native
 * Signature: (JLbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_deadUnitCount_1native__JLbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    killedUnitCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_killedUnitCount_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    killedUnitCount_native
 * Signature: (JLbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_killedUnitCount_1native__JLbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    getUpgradeLevel_native
 * Signature: (JLbwapi4/UpgradeType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_getUpgradeLevel_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    hasResearched_native
 * Signature: (JLbwapi4/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_hasResearched_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    isResearching_native
 * Signature: (JLbwapi4/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_isResearching_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    isUpgrading_native
 * Signature: (JLbwapi4/UpgradeType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_isUpgrading_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    getColor_native
 * Signature: (J)Lbwapi4/Color;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Player_getColor_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getTextColor_native
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_bwapi4_Player_getTextColor_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    maxEnergy_native
 * Signature: (JLbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_maxEnergy_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    topSpeed_native
 * Signature: (JLbwapi4/UnitType;)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi4_Player_topSpeed_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    weaponMaxRange_native
 * Signature: (JLbwapi4/WeaponType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_weaponMaxRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    sightRange_native
 * Signature: (JLbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_sightRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    weaponDamageCooldown_native
 * Signature: (JLbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_weaponDamageCooldown_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    armor_native
 * Signature: (JLbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_armor_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    damage_native
 * Signature: (JLbwapi4/WeaponType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_damage_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    getUnitScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_getUnitScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getKillScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_getKillScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getBuildingScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_getBuildingScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getRazingScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_getRazingScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getCustomScore_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_getCustomScore_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    isObserver_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_isObserver_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Player
 * Method:    getMaxUpgradeLevel_native
 * Signature: (JLbwapi4/UpgradeType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Player_getMaxUpgradeLevel_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    isResearchAvailable_native
 * Signature: (JLbwapi4/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_isResearchAvailable_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Player
 * Method:    isUnitAvailable_native
 * Signature: (JLbwapi4/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Player_isUnitAvailable_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
