/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_GameType */

#ifndef _Included_bwapi4_GameType
#define _Included_bwapi4_GameType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_GameType
 * Method:    toString_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi4_GameType_toString_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
