/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_UnitCommand */

#ifndef _Included_bwapi4_UnitCommand
#define _Included_bwapi4_UnitCommand
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
