/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_ExplosionType */

#ifndef _Included_bwapi4_ExplosionType
#define _Included_bwapi4_ExplosionType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
