/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_DefaultBWListener */

#ifndef _Included_bwapi4_DefaultBWListener
#define _Included_bwapi4_DefaultBWListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
