/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_InterfaceEvent */

#ifndef _Included_bwapi4_InterfaceEvent
#define _Included_bwapi4_InterfaceEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_InterfaceEvent
 * Method:    isFinished_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_InterfaceEvent_isFinished_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_InterfaceEvent
 * Method:    removeEvent_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi4_InterfaceEvent_removeEvent_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
