/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Regionset */

#ifndef _Included_bwapi4_Regionset
#define _Included_bwapi4_Regionset
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_Regionset
 * Method:    getCenter_native
 * Signature: (J)Lbwapi4/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Regionset_getCenter_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
