/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_DamageType */

#ifndef _Included_bwapi4_DamageType
#define _Included_bwapi4_DamageType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
