/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_BulletType */

#ifndef _Included_bwapi4_BulletType
#define _Included_bwapi4_BulletType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_BulletType
 * Method:    toString_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi4_BulletType_toString_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
