/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Point */

#ifndef _Included_bwapi4_Point
#define _Included_bwapi4_Point
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_Point
 * Method:    isValid_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Point_isValid_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Point
 * Method:    getLength_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi4_Point_getLength_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
