/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Region */

#ifndef _Included_bwapi4_Region
#define _Included_bwapi4_Region
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_Region
 * Method:    getID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Region_getID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getRegionGroupID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Region_getRegionGroupID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getCenter_native
 * Signature: (J)Lbwapi4/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Region_getCenter_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    isHigherGround_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Region_isHigherGround_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getDefensePriority_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Region_getDefensePriority_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    isAccessible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Region_isAccessible_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getNeighbors_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Region_getNeighbors_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getBoundsLeft_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Region_getBoundsLeft_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getBoundsTop_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Region_getBoundsTop_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getBoundsRight_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Region_getBoundsRight_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getBoundsBottom_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Region_getBoundsBottom_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getClosestAccessibleRegion_native
 * Signature: (J)Lbwapi4/Region;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Region_getClosestAccessibleRegion_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getClosestInaccessibleRegion_native
 * Signature: (J)Lbwapi4/Region;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Region_getClosestInaccessibleRegion_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Region
 * Method:    getDistance_native
 * Signature: (JLbwapi4/Region;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Region_getDistance_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
