/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Race */

#ifndef _Included_bwapi_Race
#define _Included_bwapi_Race
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Race
 * Method:    toString_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi_Race_toString_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Race
 * Method:    getWorker_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Race_getWorker_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Race
 * Method:    getCenter_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Race_getCenter_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Race
 * Method:    getRefinery_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Race_getRefinery_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Race
 * Method:    getTransport_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Race_getTransport_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Race
 * Method:    getSupplyProvider_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Race_getSupplyProvider_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
