/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_BWEventListener */

#ifndef _Included_bwapi4_BWEventListener
#define _Included_bwapi4_BWEventListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
