/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_UnitSizeType */

#ifndef _Included_bwapi4_UnitSizeType
#define _Included_bwapi4_UnitSizeType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
