/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Point */

#ifndef _Included_bwapi4_Point
#define _Included_bwapi4_Point
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_Point
 * Method:    isValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Point_isValid
  (JNIEnv *, jobject);

/*
 * Class:     bwapi4_Point
 * Method:    makeValid
 * Signature: ()Lbwapi4/Point;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Point_makeValid
  (JNIEnv *, jobject);

/*
 * Class:     bwapi4_Point
 * Method:    getDistance
 * Signature: (Lbwapi4/Point;)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi4_Point_getDistance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bwapi4_Point
 * Method:    getLength
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_bwapi4_Point_getLength
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
