/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_TechType */

#ifndef _Included_bwapi_TechType
#define _Included_bwapi_TechType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_TechType
 * Method:    toString_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi_TechType_toString_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    getRace_native
 * Signature: (J)Lbwapi/Race;
 */
JNIEXPORT jobject JNICALL Java_bwapi_TechType_getRace_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    mineralPrice_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_TechType_mineralPrice_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    gasPrice_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_TechType_gasPrice_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    researchTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_TechType_researchTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    energyCost_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_TechType_energyCost_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    whatResearches_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_TechType_whatResearches_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    getWeapon_native
 * Signature: (J)Lbwapi/WeaponType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_TechType_getWeapon_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    targetsUnit_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_TechType_targetsUnit_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    targetsPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_TechType_targetsPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    getOrder_native
 * Signature: (J)Lbwapi/Order;
 */
JNIEXPORT jobject JNICALL Java_bwapi_TechType_getOrder_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_TechType
 * Method:    requiredUnit_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_TechType_requiredUnit_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
