/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_UnitFilter */

#ifndef _Included_bwapi4_UnitFilter
#define _Included_bwapi4_UnitFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
