/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Game */

#ifndef _Included_bwapi4_Game
#define _Included_bwapi4_Game
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_Game
 * Method:    getForces_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getForces_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getPlayers_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getPlayers_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getAllUnits_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getAllUnits_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getMinerals_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getGeysers_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getGeysers_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getNeutralUnits_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getNeutralUnits_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getStaticMinerals_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getStaticMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getStaticGeysers_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getStaticGeysers_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getStaticNeutralUnits_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getStaticNeutralUnits_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getBullets_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getBullets_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getForce_native
 * Signature: (JI)Lbwapi4/Force;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getForce_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi4_Game
 * Method:    getPlayer_native
 * Signature: (JI)Lbwapi4/Player;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getPlayer_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi4_Game
 * Method:    getUnit_native
 * Signature: (JI)Lbwapi4/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getUnit_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi4_Game
 * Method:    indexToUnit_native
 * Signature: (JI)Lbwapi4/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_indexToUnit_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi4_Game
 * Method:    getRegion_native
 * Signature: (JI)Lbwapi4/Region;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getRegion_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi4_Game
 * Method:    getGameType_native
 * Signature: (J)Lbwapi4/GameType;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getGameType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getLatency_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getLatency_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getFrameCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getFrameCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getReplayFrameCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getReplayFrameCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getFPS_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getFPS_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getAverageFPS_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi4_Game_getAverageFPS_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getMousePosition_native
 * Signature: (J)Lbwapi4/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getMousePosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getMouseState_native
 * Signature: (JLbwapi4/MouseButton;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_getMouseState_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getKeyState_native
 * Signature: (JLbwapi4/Key;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_getKeyState_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getScreenPosition_native
 * Signature: (J)Lbwapi4/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getScreenPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setScreenPosition_native
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_setScreenPosition_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    setScreenPosition_native
 * Signature: (JLbwapi4/Position;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_setScreenPosition_1native__JLbwapi4_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    pingMinimap_native
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_pingMinimap_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    pingMinimap_native
 * Signature: (JLbwapi4/Position;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_pingMinimap_1native__JLbwapi4_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    isFlagEnabled_native
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isFlagEnabled_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi4_Game
 * Method:    enableFlag_native
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_enableFlag_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi4_Game
 * Method:    getLastError_native
 * Signature: (J)Lbwapi4/Error;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getLastError_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setLastError_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_setLastError_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setLastError_native
 * Signature: (JLbwapi4/Error;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_setLastError_1native__JLbwapi4_Error_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    mapWidth_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_mapWidth_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    mapHeight_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_mapHeight_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    mapFileName_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi4_Game_mapFileName_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    mapPathName_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi4_Game_mapPathName_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    mapName_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi4_Game_mapName_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    mapHash_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi4_Game_mapHash_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    isWalkable_native
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isWalkable_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    isWalkable_native
 * Signature: (JLbwapi4/WalkPosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isWalkable_1native__JLbwapi4_WalkPosition_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getGroundHeight_native
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getGroundHeight_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    getGroundHeight_native
 * Signature: (JLbwapi4/TilePosition;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getGroundHeight_1native__JLbwapi4_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    isBuildable_native
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isBuildable_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    isBuildable_native
 * Signature: (JIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isBuildable_1native__JIIZ
  (JNIEnv *, jobject, jlong, jint, jint, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    isBuildable_native
 * Signature: (JLbwapi4/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isBuildable_1native__JLbwapi4_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    isBuildable_native
 * Signature: (JLbwapi4/TilePosition;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isBuildable_1native__JLbwapi4_TilePosition_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    isVisible_native
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isVisible_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    isVisible_native
 * Signature: (JLbwapi4/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isVisible_1native__JLbwapi4_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    isExplored_native
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isExplored_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    isExplored_native
 * Signature: (JLbwapi4/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isExplored_1native__JLbwapi4_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    hasCreep_native
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasCreep_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    hasCreep_native
 * Signature: (JLbwapi4/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasCreep_1native__JLbwapi4_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    hasPowerPrecise_native
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPowerPrecise_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    hasPowerPrecise_native
 * Signature: (JIILbwapi4/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPowerPrecise_1native__JIILbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    hasPowerPrecise_native
 * Signature: (JLbwapi4/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPowerPrecise_1native__JLbwapi4_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    hasPowerPrecise_native
 * Signature: (JLbwapi4/Position;Lbwapi4/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPowerPrecise_1native__JLbwapi4_Position_2Lbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    hasPower_native
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPower_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    hasPower_native
 * Signature: (JIILbwapi4/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPower_1native__JIILbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    hasPower_native
 * Signature: (JLbwapi4/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPower_1native__JLbwapi4_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    hasPower_native
 * Signature: (JLbwapi4/TilePosition;Lbwapi4/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPower_1native__JLbwapi4_TilePosition_2Lbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    hasPower_native
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPower_1native__JIIII
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    hasPower_native
 * Signature: (JIIIILbwapi4/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPower_1native__JIIIILbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    hasPower_native
 * Signature: (JLbwapi4/TilePosition;II)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPower_1native__JLbwapi4_TilePosition_2II
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    hasPower_native
 * Signature: (JLbwapi4/TilePosition;IILbwapi4/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPower_1native__JLbwapi4_TilePosition_2IILbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    canBuildHere_native
 * Signature: (JLbwapi4/TilePosition;Lbwapi4/UnitType;Lbwapi4/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canBuildHere_1native__JLbwapi4_TilePosition_2Lbwapi4_UnitType_2Lbwapi4_Unit_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    canBuildHere_native
 * Signature: (JLbwapi4/TilePosition;Lbwapi4/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canBuildHere_1native__JLbwapi4_TilePosition_2Lbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    canBuildHere_native
 * Signature: (JLbwapi4/TilePosition;Lbwapi4/UnitType;Lbwapi4/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canBuildHere_1native__JLbwapi4_TilePosition_2Lbwapi4_UnitType_2Lbwapi4_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    canMake_native
 * Signature: (JLbwapi4/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canMake_1native__JLbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    canMake_native
 * Signature: (JLbwapi4/UnitType;Lbwapi4/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canMake_1native__JLbwapi4_UnitType_2Lbwapi4_Unit_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    canResearch_native
 * Signature: (JLbwapi4/TechType;Lbwapi4/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canResearch_1native__JLbwapi4_TechType_2Lbwapi4_Unit_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    canResearch_native
 * Signature: (JLbwapi4/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canResearch_1native__JLbwapi4_TechType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    canResearch_native
 * Signature: (JLbwapi4/TechType;Lbwapi4/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canResearch_1native__JLbwapi4_TechType_2Lbwapi4_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    canUpgrade_native
 * Signature: (JLbwapi4/UpgradeType;Lbwapi4/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canUpgrade_1native__JLbwapi4_UpgradeType_2Lbwapi4_Unit_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    canUpgrade_native
 * Signature: (JLbwapi4/UpgradeType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canUpgrade_1native__JLbwapi4_UpgradeType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    canUpgrade_native
 * Signature: (JLbwapi4/UpgradeType;Lbwapi4/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_canUpgrade_1native__JLbwapi4_UpgradeType_2Lbwapi4_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    printf_native
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_printf_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    sendText_native
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_sendText_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    sendTextEx_native
 * Signature: (JZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_sendTextEx_1native
  (JNIEnv *, jobject, jlong, jboolean, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    isInGame_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isInGame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    isMultiplayer_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isMultiplayer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    isBattleNet_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isBattleNet_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    isPaused_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isPaused_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    isReplay_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isReplay_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    pauseGame_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_pauseGame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    resumeGame_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_resumeGame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    leaveGame_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_leaveGame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    restartGame_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_restartGame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setLocalSpeed_native
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_setLocalSpeed_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi4_Game
 * Method:    issueCommand_native
 * Signature: (JLjava/util/List;Lbwapi4/UnitCommand;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_issueCommand_1native
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getSelectedUnits_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getSelectedUnits_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    self_native
 * Signature: (J)Lbwapi4/Player;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_self_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    enemy_native
 * Signature: (J)Lbwapi4/Player;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_enemy_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    neutral_native
 * Signature: (J)Lbwapi4/Player;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_neutral_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    allies_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_allies_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    enemies_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_enemies_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    observers_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_observers_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setTextSize_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_setTextSize_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setTextSize_native
 * Signature: (JLbwapi4/Text/Size/Enum;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_setTextSize_1native__JLbwapi4_Text_Size_Enum_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawText_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawText_1native
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    drawTextMap_native
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTextMap_1native__JIILjava_lang_String_2
  (JNIEnv *, jobject, jlong, jint, jint, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    drawTextMap_native
 * Signature: (JLbwapi4/Position;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTextMap_1native__JLbwapi4_Position_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    drawTextMouse_native
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTextMouse_1native__JIILjava_lang_String_2
  (JNIEnv *, jobject, jlong, jint, jint, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    drawTextMouse_native
 * Signature: (JLbwapi4/Position;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTextMouse_1native__JLbwapi4_Position_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    drawTextScreen_native
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTextScreen_1native__JIILjava_lang_String_2
  (JNIEnv *, jobject, jlong, jint, jint, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    drawTextScreen_native
 * Signature: (JLbwapi4/Position;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTextScreen_1native__JLbwapi4_Position_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    drawBox_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBox_1native__JLbwapi4_CoordinateType_Enum_2IIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawBox_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBox_1native__JLbwapi4_CoordinateType_Enum_2IIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxMap_native
 * Signature: (JIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxMap_1native__JIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxMap_native
 * Signature: (JIIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxMap_1native__JIIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxMap_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxMap_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxMap_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxMap_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxMouse_native
 * Signature: (JIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxMouse_1native__JIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxMouse_native
 * Signature: (JIIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxMouse_1native__JIIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxMouse_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxMouse_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxMouse_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxMouse_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxScreen_native
 * Signature: (JIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxScreen_1native__JIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxScreen_native
 * Signature: (JIIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxScreen_1native__JIIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxScreen_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxScreen_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawBoxScreen_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawBoxScreen_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangle_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IIIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangle_1native__JLbwapi4_CoordinateType_Enum_2IIIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangle_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IIIIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangle_1native__JLbwapi4_CoordinateType_Enum_2IIIIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleMap_native
 * Signature: (JIIIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleMap_1native__JIIIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleMap_native
 * Signature: (JIIIIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleMap_1native__JIIIIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleMap_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleMap_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleMap_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleMap_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleMouse_native
 * Signature: (JIIIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleMouse_1native__JIIIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleMouse_native
 * Signature: (JIIIIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleMouse_1native__JIIIIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleMouse_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleMouse_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleMouse_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleMouse_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleScreen_native
 * Signature: (JIIIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleScreen_1native__JIIIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleScreen_native
 * Signature: (JIIIIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleScreen_1native__JIIIIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleScreen_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleScreen_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawTriangleScreen_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawTriangleScreen_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircle_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircle_1native__JLbwapi4_CoordinateType_Enum_2IIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircle_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircle_1native__JLbwapi4_CoordinateType_Enum_2IIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleMap_native
 * Signature: (JIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleMap_1native__JIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleMap_native
 * Signature: (JIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleMap_1native__JIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleMap_native
 * Signature: (JLbwapi4/Position;ILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleMap_1native__JLbwapi4_Position_2ILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleMap_native
 * Signature: (JLbwapi4/Position;ILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleMap_1native__JLbwapi4_Position_2ILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleMouse_native
 * Signature: (JIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleMouse_1native__JIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleMouse_native
 * Signature: (JIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleMouse_1native__JIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleMouse_native
 * Signature: (JLbwapi4/Position;ILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleMouse_1native__JLbwapi4_Position_2ILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleMouse_native
 * Signature: (JLbwapi4/Position;ILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleMouse_1native__JLbwapi4_Position_2ILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleScreen_native
 * Signature: (JIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleScreen_1native__JIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleScreen_native
 * Signature: (JIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleScreen_1native__JIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleScreen_native
 * Signature: (JLbwapi4/Position;ILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleScreen_1native__JLbwapi4_Position_2ILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawCircleScreen_native
 * Signature: (JLbwapi4/Position;ILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawCircleScreen_1native__JLbwapi4_Position_2ILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipse_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipse_1native__JLbwapi4_CoordinateType_Enum_2IIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipse_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipse_1native__JLbwapi4_CoordinateType_Enum_2IIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseMap_native
 * Signature: (JIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseMap_1native__JIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseMap_native
 * Signature: (JIIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseMap_1native__JIIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseMap_native
 * Signature: (JLbwapi4/Position;IILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseMap_1native__JLbwapi4_Position_2IILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseMap_native
 * Signature: (JLbwapi4/Position;IILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseMap_1native__JLbwapi4_Position_2IILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseMouse_native
 * Signature: (JIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseMouse_1native__JIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseMouse_native
 * Signature: (JIIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseMouse_1native__JIIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseMouse_native
 * Signature: (JLbwapi4/Position;IILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseMouse_1native__JLbwapi4_Position_2IILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseMouse_native
 * Signature: (JLbwapi4/Position;IILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseMouse_1native__JLbwapi4_Position_2IILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseScreen_native
 * Signature: (JIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseScreen_1native__JIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseScreen_native
 * Signature: (JIIIILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseScreen_1native__JIIIILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseScreen_native
 * Signature: (JLbwapi4/Position;IILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseScreen_1native__JLbwapi4_Position_2IILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawEllipseScreen_native
 * Signature: (JLbwapi4/Position;IILbwapi4/Color;Z)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawEllipseScreen_1native__JLbwapi4_Position_2IILbwapi4_Color_2Z
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    drawDot_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawDot_1native
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawDotMap_native
 * Signature: (JIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawDotMap_1native__JIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawDotMap_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawDotMap_1native__JLbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawDotMouse_native
 * Signature: (JIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawDotMouse_1native__JIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawDotMouse_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawDotMouse_1native__JLbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawDotScreen_native
 * Signature: (JIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawDotScreen_1native__JIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawDotScreen_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawDotScreen_1native__JLbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawLine_native
 * Signature: (JLbwapi4/CoordinateType/Enum;IIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawLine_1native
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawLineMap_native
 * Signature: (JIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawLineMap_1native__JIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawLineMap_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawLineMap_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawLineMouse_native
 * Signature: (JIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawLineMouse_1native__JIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawLineMouse_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawLineMouse_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawLineScreen_native
 * Signature: (JIIIILbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawLineScreen_1native__JIIIILbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    drawLineScreen_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;Lbwapi4/Color;)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_drawLineScreen_1native__JLbwapi4_Position_2Lbwapi4_Position_2Lbwapi4_Color_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getLatencyFrames_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getLatencyFrames_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getLatencyTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getLatencyTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getRemainingLatencyFrames_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getRemainingLatencyFrames_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getRemainingLatencyTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getRemainingLatencyTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getRevision_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getRevision_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    isDebug_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isDebug_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    isLatComEnabled_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isLatComEnabled_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setLatCom_native
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_setLatCom_1native
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    isGUIEnabled_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_isGUIEnabled_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setGUI_native
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_setGUI_1native
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    getInstanceNumber_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getInstanceNumber_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getAPM_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getAPM_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getAPM_native
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getAPM_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    setMap_native
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_setMap_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     bwapi4_Game
 * Method:    setFrameSkip_native
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_setFrameSkip_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi4_Game
 * Method:    hasPath_native
 * Signature: (JLbwapi4/Position;Lbwapi4/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_hasPath_1native
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    setAlliance_native
 * Signature: (JLbwapi4/Player;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_setAlliance_1native__JLbwapi4_Player_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    setAlliance_native
 * Signature: (JLbwapi4/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_setAlliance_1native__JLbwapi4_Player_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    setAlliance_native
 * Signature: (JLbwapi4/Player;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_setAlliance_1native__JLbwapi4_Player_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    setVision_native
 * Signature: (JLbwapi4/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_setVision_1native__JLbwapi4_Player_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    setVision_native
 * Signature: (JLbwapi4/Player;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_setVision_1native__JLbwapi4_Player_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    elapsedTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_elapsedTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setCommandOptimizationLevel_native
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bwapi4_Game_setCommandOptimizationLevel_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi4_Game
 * Method:    countdownTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_countdownTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    getRegionAt_native
 * Signature: (JII)Lbwapi4/Region;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getRegionAt_1native__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     bwapi4_Game
 * Method:    getRegionAt_native
 * Signature: (JLbwapi4/Position;)Lbwapi4/Region;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getRegionAt_1native__JLbwapi4_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getLastEventTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getLastEventTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setRevealAll_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_setRevealAll_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Game
 * Method:    setRevealAll_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Game_setRevealAll_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    getBuildLocation_native
 * Signature: (JLbwapi4/UnitType;Lbwapi4/TilePosition;I)Lbwapi4/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getBuildLocation_1native__JLbwapi4_UnitType_2Lbwapi4_TilePosition_2I
  (JNIEnv *, jobject, jlong, jobject, jobject, jint);

/*
 * Class:     bwapi4_Game
 * Method:    getBuildLocation_native
 * Signature: (JLbwapi4/UnitType;Lbwapi4/TilePosition;)Lbwapi4/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getBuildLocation_1native__JLbwapi4_UnitType_2Lbwapi4_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getBuildLocation_native
 * Signature: (JLbwapi4/UnitType;Lbwapi4/TilePosition;IZ)Lbwapi4/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Game_getBuildLocation_1native__JLbwapi4_UnitType_2Lbwapi4_TilePosition_2IZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jint, jboolean);

/*
 * Class:     bwapi4_Game
 * Method:    getDamageFrom_native
 * Signature: (JLbwapi4/UnitType;Lbwapi4/UnitType;Lbwapi4/Player;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getDamageFrom_1native__JLbwapi4_UnitType_2Lbwapi4_UnitType_2Lbwapi4_Player_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getDamageFrom_native
 * Signature: (JLbwapi4/UnitType;Lbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getDamageFrom_1native__JLbwapi4_UnitType_2Lbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getDamageFrom_native
 * Signature: (JLbwapi4/UnitType;Lbwapi4/UnitType;Lbwapi4/Player;Lbwapi4/Player;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getDamageFrom_1native__JLbwapi4_UnitType_2Lbwapi4_UnitType_2Lbwapi4_Player_2Lbwapi4_Player_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getDamageTo_native
 * Signature: (JLbwapi4/UnitType;Lbwapi4/UnitType;Lbwapi4/Player;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getDamageTo_1native__JLbwapi4_UnitType_2Lbwapi4_UnitType_2Lbwapi4_Player_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getDamageTo_native
 * Signature: (JLbwapi4/UnitType;Lbwapi4/UnitType;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getDamageTo_1native__JLbwapi4_UnitType_2Lbwapi4_UnitType_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi4_Game
 * Method:    getDamageTo_native
 * Signature: (JLbwapi4/UnitType;Lbwapi4/UnitType;Lbwapi4/Player;Lbwapi4/Player;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_Game_getDamageTo_1native__JLbwapi4_UnitType_2Lbwapi4_UnitType_2Lbwapi4_Player_2Lbwapi4_Player_2
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
