/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_UnitCommandType */

#ifndef _Included_bwapi4_UnitCommandType
#define _Included_bwapi4_UnitCommandType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
