/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_CompareFilter */

#ifndef _Included_bwapi_CompareFilter
#define _Included_bwapi_CompareFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
