/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_PlayerType */

#ifndef _Included_bwapi_PlayerType
#define _Included_bwapi_PlayerType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_PlayerType
 * Method:    toString_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi_PlayerType_toString_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerType
 * Method:    isLobbyType_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerType_isLobbyType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_PlayerType
 * Method:    isGameType_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_PlayerType_isGameType_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
