/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_WalkPosition */

#ifndef _Included_bwapi_WalkPosition
#define _Included_bwapi_WalkPosition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_WalkPosition
 * Method:    isValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_WalkPosition_isValid
  (JNIEnv *, jobject);

/*
 * Class:     bwapi_WalkPosition
 * Method:    makeValid
 * Signature: ()Lbwapi/WalkPosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi_WalkPosition_makeValid
  (JNIEnv *, jobject);

/*
 * Class:     bwapi_WalkPosition
 * Method:    getApproxDistance
 * Signature: (Lbwapi/WalkPosition;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_WalkPosition_getApproxDistance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bwapi_WalkPosition
 * Method:    getLength
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_WalkPosition_getLength
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
