/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_BestUnitFilter */

#ifndef _Included_bwapi4_BestUnitFilter
#define _Included_bwapi4_BestUnitFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
