/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_PlayerType */

#ifndef _Included_bwapi4_PlayerType
#define _Included_bwapi4_PlayerType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
