/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Mirror */

#ifndef _Included_bwapi4_Mirror
#define _Included_bwapi4_Mirror
#ifdef __cplusplus
extern "C" {
#endif
#undef bwapi4_Mirror_EXTRACT_JAR
#define bwapi4_Mirror_EXTRACT_JAR 1L
/*
 * Class:     bwapi4_Mirror
 * Method:    startGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bwapi4_Mirror_startGame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
