/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Bullet */

#ifndef _Included_bwapi_Bullet
#define _Included_bwapi_Bullet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Bullet
 * Method:    getID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Bullet_getID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    exists_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Bullet_exists_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    getPlayer_native
 * Signature: (J)Lbwapi/Player;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Bullet_getPlayer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    getType_native
 * Signature: (J)Lbwapi/BulletType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Bullet_getType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    getSource_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Bullet_getSource_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    getPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Bullet_getPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    getAngle_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Bullet_getAngle_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    getVelocityX_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Bullet_getVelocityX_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    getVelocityY_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Bullet_getVelocityY_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    getTarget_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Bullet_getTarget_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    getTargetPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Bullet_getTargetPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    getRemoveTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Bullet_getRemoveTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    isVisible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Bullet_isVisible_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Bullet
 * Method:    isVisible_native
 * Signature: (JLbwapi/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Bullet_isVisible_1native__JLbwapi_Player_2
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
