/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Client */

#ifndef _Included_bwapi_Client
#define _Included_bwapi_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Client
 * Method:    isConnected_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Client_isConnected_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Client
 * Method:    connect_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Client_connect_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Client
 * Method:    disconnect_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi_Client_disconnect_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Client
 * Method:    update_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bwapi_Client_update_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
