/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Mirror_FrameCallback */

#ifndef _Included_bwapi4_Mirror_FrameCallback
#define _Included_bwapi4_Mirror_FrameCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
