/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_Unit */

#ifndef _Included_bwapi_Unit
#define _Included_bwapi_Unit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_Unit
 * Method:    getID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    exists_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_exists_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getReplayID_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getReplayID_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getPlayer_native
 * Signature: (J)Lbwapi/Player;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getPlayer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getType_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTilePosition_native
 * Signature: (J)Lbwapi/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getTilePosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getAngle_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Unit_getAngle_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getVelocityX_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Unit_getVelocityX_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getVelocityY_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_Unit_getVelocityY_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRegion_native
 * Signature: (J)Lbwapi/Region;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getRegion_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLeft_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getLeft_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTop_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getTop_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRight_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRight_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getBottom_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getBottom_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getHitPoints_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getHitPoints_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getShields_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getShields_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getEnergy_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getEnergy_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getResources_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getResources_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getResourceGroup_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getResourceGroup_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getDistance_native
 * Signature: (JLbwapi/PositionOrUnit;)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getDistance_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    hasPath_native
 * Signature: (JLbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_hasPath_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    getLastCommandFrame_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getLastCommandFrame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLastCommand_native
 * Signature: (J)Lbwapi/UnitCommand;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getLastCommand_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLastAttackingPlayer_native
 * Signature: (J)Lbwapi/Player;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getLastAttackingPlayer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInitialType_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getInitialType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInitialPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getInitialPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInitialTilePosition_native
 * Signature: (J)Lbwapi/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getInitialTilePosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInitialHitPoints_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getInitialHitPoints_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInitialResources_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getInitialResources_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getKillCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getKillCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getAcidSporeCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getAcidSporeCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInterceptorCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getInterceptorCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getScarabCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getScarabCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getSpiderMineCount_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getSpiderMineCount_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getGroundWeaponCooldown_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getGroundWeaponCooldown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getAirWeaponCooldown_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getAirWeaponCooldown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getSpellCooldown_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getSpellCooldown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getDefenseMatrixPoints_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getDefenseMatrixPoints_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getDefenseMatrixTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getDefenseMatrixTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getEnsnareTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getEnsnareTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getIrradiateTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getIrradiateTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLockdownTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getLockdownTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getMaelstromTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getMaelstromTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getOrderTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getOrderTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getPlagueTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getPlagueTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRemoveTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRemoveTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getStasisTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getStasisTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getStimTimer_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getStimTimer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getBuildType_native
 * Signature: (J)Lbwapi/UnitType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getBuildType_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTech_native
 * Signature: (J)Lbwapi/TechType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getTech_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getUpgrade_native
 * Signature: (J)Lbwapi/UpgradeType;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getUpgrade_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRemainingBuildTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRemainingBuildTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRemainingTrainTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRemainingTrainTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRemainingResearchTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRemainingResearchTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRemainingUpgradeTime_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getRemainingUpgradeTime_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getBuildUnit_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getBuildUnit_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTarget_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getTarget_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTargetPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getTargetPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getOrder_native
 * Signature: (J)Lbwapi/Order;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getOrder_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getSecondaryOrder_native
 * Signature: (J)Lbwapi/Order;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getSecondaryOrder_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getOrderTarget_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getOrderTarget_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getOrderTargetPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getOrderTargetPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRallyPosition_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getRallyPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getRallyUnit_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getRallyUnit_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getAddon_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getAddon_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getNydusExit_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getNydusExit_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getPowerUp_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getPowerUp_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getTransport_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getTransport_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLoadedUnits_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getLoadedUnits_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getSpaceRemaining_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bwapi_Unit_getSpaceRemaining_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getCarrier_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getCarrier_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getInterceptors_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getInterceptors_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getHatchery_native
 * Signature: (J)Lbwapi/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getHatchery_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    getLarva_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwapi_Unit_getLarva_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    hasNuke_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_hasNuke_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isAccelerating_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isAccelerating_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isAttacking_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isAttacking_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isAttackFrame_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isAttackFrame_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBeingConstructed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBeingConstructed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBeingGathered_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBeingGathered_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBeingHealed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBeingHealed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBlind_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBlind_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBraking_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBraking_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isBurrowed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isBurrowed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isCarryingGas_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isCarryingGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isCarryingMinerals_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isCarryingMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isCloaked_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isCloaked_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isCompleted_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isCompleted_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isConstructing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isConstructing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isDefenseMatrixed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isDefenseMatrixed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isDetected_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isDetected_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isEnsnared_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isEnsnared_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isFlying_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isFlying_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isFollowing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isFollowing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isGatheringGas_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isGatheringGas_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isGatheringMinerals_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isGatheringMinerals_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isHallucination_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isHallucination_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isHoldingPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isHoldingPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isIdle_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isIdle_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isInterruptible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isInterruptible_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isInvincible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isInvincible_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isInWeaponRange_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isInWeaponRange_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    isIrradiated_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isIrradiated_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isLifted_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isLifted_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isLoaded_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isLoaded_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isLockedDown_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isLockedDown_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isMaelstrommed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isMaelstrommed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isMorphing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isMorphing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isMoving_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isMoving_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isParasited_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isParasited_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isPatrolling_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isPatrolling_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isPlagued_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isPlagued_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isRepairing_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isRepairing_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isResearching_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isResearching_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isSelected_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isSelected_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isSieged_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isSieged_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isStartingAttack_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isStartingAttack_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isStasised_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isStasised_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isStimmed_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isStimmed_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isStuck_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isStuck_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isTraining_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isTraining_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUnderAttack_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUnderAttack_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUnderDarkSwarm_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUnderDarkSwarm_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUnderDisruptionWeb_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUnderDisruptionWeb_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUnderStorm_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUnderStorm_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isPowered_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isPowered_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isUpgrading_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isUpgrading_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isVisible_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isVisible_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    isVisible_native
 * Signature: (JLbwapi/Player;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isVisible_1native__JLbwapi_Player_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    isTargetable_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_isTargetable_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    issueCommand_native
 * Signature: (JLbwapi/UnitCommand;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_issueCommand_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    attack_native
 * Signature: (JLbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_attack_1native__JLbwapi_PositionOrUnit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    attack_native
 * Signature: (JLbwapi/PositionOrUnit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_attack_1native__JLbwapi_PositionOrUnit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    build_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_build_1native__JLbwapi_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    build_native
 * Signature: (JLbwapi/UnitType;Lbwapi/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_build_1native__JLbwapi_UnitType_2Lbwapi_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    buildAddon_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_buildAddon_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    train_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_train_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    train_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_train_1native__JLbwapi_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    morph_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_morph_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    research_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_research_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    upgrade_native
 * Signature: (JLbwapi/UpgradeType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_upgrade_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    setRallyPoint_native
 * Signature: (JLbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_setRallyPoint_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    move_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_move_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    move_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_move_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    patrol_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_patrol_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    patrol_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_patrol_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    holdPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_holdPosition_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    holdPosition_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_holdPosition_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    stop_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_stop_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    stop_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_stop_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    follow_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_follow_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    follow_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_follow_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    gather_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_gather_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    gather_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_gather_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    returnCargo_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_returnCargo_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    returnCargo_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_returnCargo_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    repair_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_repair_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    repair_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_repair_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    burrow_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_burrow_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    unburrow_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unburrow_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cloak_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cloak_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    decloak_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_decloak_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    siege_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_siege_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    unsiege_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unsiege_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    lift_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_lift_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    land_native
 * Signature: (JLbwapi/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_land_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    load_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_load_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    load_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_load_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    unload_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unload_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    unloadAll_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unloadAll_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    unloadAll_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unloadAll_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    unloadAll_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unloadAll_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    unloadAll_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_unloadAll_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    rightClick_native
 * Signature: (JLbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_rightClick_1native__JLbwapi_PositionOrUnit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    rightClick_native
 * Signature: (JLbwapi/PositionOrUnit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_rightClick_1native__JLbwapi_PositionOrUnit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    haltConstruction_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_haltConstruction_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelConstruction_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelConstruction_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelAddon_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelAddon_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelTrain_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelTrain_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelTrain_native
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelTrain_1native__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi_Unit
 * Method:    cancelMorph_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelMorph_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelResearch_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelResearch_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    cancelUpgrade_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_cancelUpgrade_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    useTech_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_useTech_1native__JLbwapi_TechType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    useTech_native
 * Signature: (JLbwapi/TechType;Lbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_useTech_1native__JLbwapi_TechType_2Lbwapi_PositionOrUnit_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    placeCOP_native
 * Signature: (JLbwapi/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_placeCOP_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommand_native
 * Signature: (JLbwapi/UnitCommand;ZZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommand_1native__JLbwapi_UnitCommand_2ZZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommand_native
 * Signature: (JLbwapi/UnitCommand;ZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommand_1native__JLbwapi_UnitCommand_2ZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommand_native
 * Signature: (JLbwapi/UnitCommand;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommand_1native__JLbwapi_UnitCommand_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommand_native
 * Signature: (JLbwapi/UnitCommand;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommand_1native__JLbwapi_UnitCommand_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommand_native
 * Signature: (JLbwapi/UnitCommand;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommand_1native__JLbwapi_UnitCommand_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommand_native
 * Signature: (JLbwapi/UnitCommand;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommand_1native__JLbwapi_UnitCommand_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommand_native
 * Signature: (JLbwapi/UnitCommand;ZZZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommand_1native__JLbwapi_UnitCommand_2ZZZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandGrouped_native
 * Signature: (JLbwapi/UnitCommand;ZZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandGrouped_1native__JLbwapi_UnitCommand_2ZZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandGrouped_native
 * Signature: (JLbwapi/UnitCommand;ZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandGrouped_1native__JLbwapi_UnitCommand_2ZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandGrouped_native
 * Signature: (JLbwapi/UnitCommand;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandGrouped_1native__JLbwapi_UnitCommand_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandGrouped_native
 * Signature: (JLbwapi/UnitCommand;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandGrouped_1native__JLbwapi_UnitCommand_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandGrouped_native
 * Signature: (JLbwapi/UnitCommand;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandGrouped_1native__JLbwapi_UnitCommand_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandGrouped_native
 * Signature: (JLbwapi/UnitCommand;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandGrouped_1native__JLbwapi_UnitCommand_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandGrouped_native
 * Signature: (JLbwapi/UnitCommand;ZZZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandGrouped_1native__JLbwapi_UnitCommand_2ZZZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCommand_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCommand_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canCommandGrouped_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCommandGrouped_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canCommandGrouped_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCommandGrouped_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandType_native
 * Signature: (JLbwapi/UnitCommandType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandType_1native__JLbwapi_UnitCommandType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandType_native
 * Signature: (JLbwapi/UnitCommandType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandType_1native__JLbwapi_UnitCommandType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandTypeGrouped_native
 * Signature: (JLbwapi/UnitCommandType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandTypeGrouped_1native__JLbwapi_UnitCommandType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandTypeGrouped_native
 * Signature: (JLbwapi/UnitCommandType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandTypeGrouped_1native__JLbwapi_UnitCommandType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canIssueCommandTypeGrouped_native
 * Signature: (JLbwapi/UnitCommandType;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canIssueCommandTypeGrouped_1native__JLbwapi_UnitCommandType_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canTargetUnit_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canTargetUnit_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canTargetUnit_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canTargetUnit_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttack_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttack_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canAttack_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttack_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttack_native
 * Signature: (JLbwapi/PositionOrUnit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttack_1native__JLbwapi_PositionOrUnit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttack_native
 * Signature: (JLbwapi/PositionOrUnit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttack_1native__JLbwapi_PositionOrUnit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttack_native
 * Signature: (JLbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttack_1native__JLbwapi_PositionOrUnit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canAttack_native
 * Signature: (JLbwapi/PositionOrUnit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttack_1native__JLbwapi_PositionOrUnit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackGrouped_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackGrouped_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackGrouped_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackGrouped_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackGrouped_native
 * Signature: (JZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackGrouped_1native__JZZ
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackGrouped_native
 * Signature: (JLbwapi/PositionOrUnit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackGrouped_1native__JLbwapi_PositionOrUnit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackGrouped_native
 * Signature: (JLbwapi/PositionOrUnit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackGrouped_1native__JLbwapi_PositionOrUnit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackGrouped_native
 * Signature: (JLbwapi/PositionOrUnit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackGrouped_1native__JLbwapi_PositionOrUnit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackGrouped_native
 * Signature: (JLbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackGrouped_1native__JLbwapi_PositionOrUnit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackGrouped_native
 * Signature: (JLbwapi/PositionOrUnit;ZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackGrouped_1native__JLbwapi_PositionOrUnit_2ZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackMove_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackMove_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackMove_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackMove_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackMoveGrouped_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackMoveGrouped_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackMoveGrouped_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackMoveGrouped_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackMoveGrouped_native
 * Signature: (JZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackMoveGrouped_1native__JZZ
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnit_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnit_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnit_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnit_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnit_native
 * Signature: (JLbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnit_1native__JLbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnit_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnit_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnit_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnit_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnit_native
 * Signature: (JLbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnit_1native__JLbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnitGrouped_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnitGrouped_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnitGrouped_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnitGrouped_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnitGrouped_native
 * Signature: (JZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnitGrouped_1native__JZZ
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnitGrouped_native
 * Signature: (JLbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnitGrouped_1native__JLbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnitGrouped_native
 * Signature: (JLbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnitGrouped_1native__JLbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnitGrouped_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnitGrouped_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnitGrouped_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnitGrouped_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canAttackUnitGrouped_native
 * Signature: (JLbwapi/Unit;ZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canAttackUnitGrouped_1native__JLbwapi_Unit_2ZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canBuild_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuild_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canBuild_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuild_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canBuild_native
 * Signature: (JLbwapi/UnitType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuild_1native__JLbwapi_UnitType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canBuild_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuild_1native__JLbwapi_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canBuild_native
 * Signature: (JLbwapi/UnitType;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuild_1native__JLbwapi_UnitType_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canBuild_native
 * Signature: (JLbwapi/UnitType;Lbwapi/TilePosition;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuild_1native__JLbwapi_UnitType_2Lbwapi_TilePosition_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canBuild_native
 * Signature: (JLbwapi/UnitType;Lbwapi/TilePosition;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuild_1native__JLbwapi_UnitType_2Lbwapi_TilePosition_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canBuild_native
 * Signature: (JLbwapi/UnitType;Lbwapi/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuild_1native__JLbwapi_UnitType_2Lbwapi_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canBuild_native
 * Signature: (JLbwapi/UnitType;Lbwapi/TilePosition;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuild_1native__JLbwapi_UnitType_2Lbwapi_TilePosition_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canBuildAddon_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuildAddon_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canBuildAddon_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuildAddon_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canBuildAddon_native
 * Signature: (JLbwapi/UnitType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuildAddon_1native__JLbwapi_UnitType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canBuildAddon_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuildAddon_1native__JLbwapi_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canBuildAddon_native
 * Signature: (JLbwapi/UnitType;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBuildAddon_1native__JLbwapi_UnitType_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canTrain_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canTrain_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canTrain_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canTrain_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canTrain_native
 * Signature: (JLbwapi/UnitType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canTrain_1native__JLbwapi_UnitType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canTrain_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canTrain_1native__JLbwapi_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canTrain_native
 * Signature: (JLbwapi/UnitType;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canTrain_1native__JLbwapi_UnitType_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canMorph_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canMorph_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canMorph_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canMorph_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canMorph_native
 * Signature: (JLbwapi/UnitType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canMorph_1native__JLbwapi_UnitType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canMorph_native
 * Signature: (JLbwapi/UnitType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canMorph_1native__JLbwapi_UnitType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canMorph_native
 * Signature: (JLbwapi/UnitType;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canMorph_1native__JLbwapi_UnitType_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canResearch_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canResearch_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canResearch_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canResearch_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canResearch_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canResearch_1native__JLbwapi_TechType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canResearch_native
 * Signature: (JLbwapi/TechType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canResearch_1native__JLbwapi_TechType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUpgrade_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUpgrade_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canUpgrade_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUpgrade_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUpgrade_native
 * Signature: (JLbwapi/UpgradeType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUpgrade_1native__JLbwapi_UpgradeType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUpgrade_native
 * Signature: (JLbwapi/UpgradeType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUpgrade_1native__JLbwapi_UpgradeType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyPoint_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyPoint_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyPoint_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyPoint_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyPoint_native
 * Signature: (JLbwapi/PositionOrUnit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyPoint_1native__JLbwapi_PositionOrUnit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyPoint_native
 * Signature: (JLbwapi/PositionOrUnit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyPoint_1native__JLbwapi_PositionOrUnit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyPoint_native
 * Signature: (JLbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyPoint_1native__JLbwapi_PositionOrUnit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyPoint_native
 * Signature: (JLbwapi/PositionOrUnit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyPoint_1native__JLbwapi_PositionOrUnit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyPosition_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyPosition_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyPosition_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyUnit_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyUnit_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyUnit_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyUnit_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyUnit_native
 * Signature: (JLbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyUnit_1native__JLbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyUnit_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyUnit_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyUnit_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyUnit_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canSetRallyUnit_native
 * Signature: (JLbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSetRallyUnit_1native__JLbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canMove_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canMove_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canMove_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canMove_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canMoveGrouped_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canMoveGrouped_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canMoveGrouped_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canMoveGrouped_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canMoveGrouped_native
 * Signature: (JZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canMoveGrouped_1native__JZZ
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canPatrol_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canPatrol_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canPatrol_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canPatrol_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canPatrolGrouped_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canPatrolGrouped_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canPatrolGrouped_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canPatrolGrouped_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canPatrolGrouped_native
 * Signature: (JZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canPatrolGrouped_1native__JZZ
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canFollow_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canFollow_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canFollow_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canFollow_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canFollow_native
 * Signature: (JLbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canFollow_1native__JLbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canFollow_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canFollow_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canFollow_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canFollow_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canFollow_native
 * Signature: (JLbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canFollow_1native__JLbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canGather_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canGather_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canGather_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canGather_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canGather_native
 * Signature: (JLbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canGather_1native__JLbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canGather_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canGather_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canGather_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canGather_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canGather_native
 * Signature: (JLbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canGather_1native__JLbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canReturnCargo_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canReturnCargo_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canReturnCargo_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canReturnCargo_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canHoldPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canHoldPosition_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canHoldPosition_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canHoldPosition_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canStop_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canStop_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canStop_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canStop_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRepair_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRepair_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canRepair_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRepair_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRepair_native
 * Signature: (JLbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRepair_1native__JLbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRepair_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRepair_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRepair_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRepair_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canRepair_native
 * Signature: (JLbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRepair_1native__JLbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canBurrow_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBurrow_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canBurrow_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canBurrow_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnburrow_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnburrow_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canUnburrow_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnburrow_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCloak_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCloak_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canCloak_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCloak_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canDecloak_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canDecloak_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canDecloak_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canDecloak_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canSiege_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSiege_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canSiege_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canSiege_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnsiege_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnsiege_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canUnsiege_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnsiege_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canLift_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLift_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canLift_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLift_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canLand_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLand_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canLand_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLand_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canLand_native
 * Signature: (JLbwapi/TilePosition;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLand_1native__JLbwapi_TilePosition_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canLand_native
 * Signature: (JLbwapi/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLand_1native__JLbwapi_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canLand_native
 * Signature: (JLbwapi/TilePosition;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLand_1native__JLbwapi_TilePosition_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canLoad_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLoad_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canLoad_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLoad_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canLoad_native
 * Signature: (JLbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLoad_1native__JLbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canLoad_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLoad_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canLoad_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLoad_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canLoad_native
 * Signature: (JLbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canLoad_1native__JLbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadWithOrWithoutTarget_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadWithOrWithoutTarget_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadWithOrWithoutTarget_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadWithOrWithoutTarget_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadAtPosition_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadAtPosition_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadAtPosition_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadAtPosition_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadAtPosition_native
 * Signature: (JLbwapi/Position;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadAtPosition_1native__JLbwapi_Position_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnload_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnload_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canUnload_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnload_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnload_native
 * Signature: (JLbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnload_1native__JLbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnload_native
 * Signature: (JLbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnload_1native__JLbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnload_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnload_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnload_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnload_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUnload_native
 * Signature: (JLbwapi/Unit;ZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnload_1native__JLbwapi_Unit_2ZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadAll_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadAll_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadAll_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadAll_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadAllPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadAllPosition_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadAllPosition_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadAllPosition_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadAllPosition_native
 * Signature: (JLbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadAllPosition_1native__JLbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadAllPosition_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadAllPosition_1native__JLbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUnloadAllPosition_native
 * Signature: (JLbwapi/Position;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUnloadAllPosition_1native__JLbwapi_Position_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClick_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClick_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClick_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClick_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClick_native
 * Signature: (JLbwapi/PositionOrUnit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClick_1native__JLbwapi_PositionOrUnit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClick_native
 * Signature: (JLbwapi/PositionOrUnit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClick_1native__JLbwapi_PositionOrUnit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClick_native
 * Signature: (JLbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClick_1native__JLbwapi_PositionOrUnit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClick_native
 * Signature: (JLbwapi/PositionOrUnit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClick_1native__JLbwapi_PositionOrUnit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickGrouped_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickGrouped_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickGrouped_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickGrouped_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickGrouped_native
 * Signature: (JZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickGrouped_1native__JZZ
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickGrouped_native
 * Signature: (JLbwapi/PositionOrUnit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickGrouped_1native__JLbwapi_PositionOrUnit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickGrouped_native
 * Signature: (JLbwapi/PositionOrUnit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickGrouped_1native__JLbwapi_PositionOrUnit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickGrouped_native
 * Signature: (JLbwapi/PositionOrUnit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickGrouped_1native__JLbwapi_PositionOrUnit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickGrouped_native
 * Signature: (JLbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickGrouped_1native__JLbwapi_PositionOrUnit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickGrouped_native
 * Signature: (JLbwapi/PositionOrUnit;ZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickGrouped_1native__JLbwapi_PositionOrUnit_2ZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickPosition_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickPosition_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickPosition_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickPosition_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickPositionGrouped_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickPositionGrouped_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickPositionGrouped_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickPositionGrouped_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickPositionGrouped_native
 * Signature: (JZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickPositionGrouped_1native__JZZ
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnit_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnit_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnit_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnit_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnit_native
 * Signature: (JLbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnit_1native__JLbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnit_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnit_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnit_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnit_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnit_native
 * Signature: (JLbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnit_1native__JLbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnitGrouped_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnitGrouped_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnitGrouped_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnitGrouped_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnitGrouped_native
 * Signature: (JZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnitGrouped_1native__JZZ
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnitGrouped_native
 * Signature: (JLbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnitGrouped_1native__JLbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnitGrouped_native
 * Signature: (JLbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnitGrouped_1native__JLbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnitGrouped_native
 * Signature: (JLbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnitGrouped_1native__JLbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnitGrouped_native
 * Signature: (JLbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnitGrouped_1native__JLbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canRightClickUnitGrouped_native
 * Signature: (JLbwapi/Unit;ZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canRightClickUnitGrouped_1native__JLbwapi_Unit_2ZZZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canHaltConstruction_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canHaltConstruction_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canHaltConstruction_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canHaltConstruction_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelConstruction_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelConstruction_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelConstruction_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelConstruction_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelAddon_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelAddon_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelAddon_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelAddon_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelTrain_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelTrain_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelTrain_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelTrain_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelTrainSlot_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelTrainSlot_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelTrainSlot_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelTrainSlot_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelTrainSlot_native
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelTrainSlot_1native__JIZ
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelTrainSlot_native
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelTrainSlot_1native__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelTrainSlot_native
 * Signature: (JIZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelTrainSlot_1native__JIZZ
  (JNIEnv *, jobject, jlong, jint, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelMorph_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelMorph_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelMorph_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelMorph_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelResearch_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelResearch_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelResearch_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelResearch_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelUpgrade_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelUpgrade_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canCancelUpgrade_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canCancelUpgrade_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechWithOrWithoutTarget_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechWithOrWithoutTarget_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechWithOrWithoutTarget_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechWithOrWithoutTarget_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechWithOrWithoutTarget_native
 * Signature: (JLbwapi/TechType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechWithOrWithoutTarget_1native__JLbwapi_TechType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechWithOrWithoutTarget_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechWithOrWithoutTarget_1native__JLbwapi_TechType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechWithOrWithoutTarget_native
 * Signature: (JLbwapi/TechType;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechWithOrWithoutTarget_1native__JLbwapi_TechType_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTech_native
 * Signature: (JLbwapi/TechType;Lbwapi/PositionOrUnit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTech_1native__JLbwapi_TechType_2Lbwapi_PositionOrUnit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTech_native
 * Signature: (JLbwapi/TechType;Lbwapi/PositionOrUnit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTech_1native__JLbwapi_TechType_2Lbwapi_PositionOrUnit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTech_native
 * Signature: (JLbwapi/TechType;Lbwapi/PositionOrUnit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTech_1native__JLbwapi_TechType_2Lbwapi_PositionOrUnit_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTech_native
 * Signature: (JLbwapi/TechType;Lbwapi/PositionOrUnit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTech_1native__JLbwapi_TechType_2Lbwapi_PositionOrUnit_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTech_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTech_1native__JLbwapi_TechType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTech_native
 * Signature: (JLbwapi/TechType;Lbwapi/PositionOrUnit;ZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTech_1native__JLbwapi_TechType_2Lbwapi_PositionOrUnit_2ZZZZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechWithoutTarget_native
 * Signature: (JLbwapi/TechType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechWithoutTarget_1native__JLbwapi_TechType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechWithoutTarget_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechWithoutTarget_1native__JLbwapi_TechType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechWithoutTarget_native
 * Signature: (JLbwapi/TechType;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechWithoutTarget_1native__JLbwapi_TechType_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechUnit_native
 * Signature: (JLbwapi/TechType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechUnit_1native__JLbwapi_TechType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechUnit_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechUnit_1native__JLbwapi_TechType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechUnit_native
 * Signature: (JLbwapi/TechType;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechUnit_1native__JLbwapi_TechType_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechUnit_native
 * Signature: (JLbwapi/TechType;Lbwapi/Unit;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechUnit_1native__JLbwapi_TechType_2Lbwapi_Unit_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechUnit_native
 * Signature: (JLbwapi/TechType;Lbwapi/Unit;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechUnit_1native__JLbwapi_TechType_2Lbwapi_Unit_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechUnit_native
 * Signature: (JLbwapi/TechType;Lbwapi/Unit;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechUnit_1native__JLbwapi_TechType_2Lbwapi_Unit_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechUnit_native
 * Signature: (JLbwapi/TechType;Lbwapi/Unit;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechUnit_1native__JLbwapi_TechType_2Lbwapi_Unit_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechUnit_native
 * Signature: (JLbwapi/TechType;Lbwapi/Unit;ZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechUnit_1native__JLbwapi_TechType_2Lbwapi_Unit_2ZZZZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechPosition_native
 * Signature: (JLbwapi/TechType;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechPosition_1native__JLbwapi_TechType_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechPosition_native
 * Signature: (JLbwapi/TechType;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechPosition_1native__JLbwapi_TechType_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechPosition_native
 * Signature: (JLbwapi/TechType;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechPosition_1native__JLbwapi_TechType_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechPosition_native
 * Signature: (JLbwapi/TechType;Lbwapi/Position;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechPosition_1native__JLbwapi_TechType_2Lbwapi_Position_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechPosition_native
 * Signature: (JLbwapi/TechType;Lbwapi/Position;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechPosition_1native__JLbwapi_TechType_2Lbwapi_Position_2Z
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechPosition_native
 * Signature: (JLbwapi/TechType;Lbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechPosition_1native__JLbwapi_TechType_2Lbwapi_Position_2
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canUseTechPosition_native
 * Signature: (JLbwapi/TechType;Lbwapi/Position;ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canUseTechPosition_1native__JLbwapi_TechType_2Lbwapi_Position_2ZZZ
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canPlaceCOP_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canPlaceCOP_1native__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi_Unit
 * Method:    canPlaceCOP_native
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canPlaceCOP_1native__JZ
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canPlaceCOP_native
 * Signature: (JLbwapi/TilePosition;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canPlaceCOP_1native__JLbwapi_TilePosition_2Z
  (JNIEnv *, jobject, jlong, jobject, jboolean);

/*
 * Class:     bwapi_Unit
 * Method:    canPlaceCOP_native
 * Signature: (JLbwapi/TilePosition;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canPlaceCOP_1native__JLbwapi_TilePosition_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwapi_Unit
 * Method:    canPlaceCOP_native
 * Signature: (JLbwapi/TilePosition;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_Unit_canPlaceCOP_1native__JLbwapi_TilePosition_2ZZ
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
