/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_WalkPosition */

#ifndef _Included_bwapi4_WalkPosition
#define _Included_bwapi4_WalkPosition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_WalkPosition
 * Method:    isValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_WalkPosition_isValid
  (JNIEnv *, jobject);

/*
 * Class:     bwapi4_WalkPosition
 * Method:    makeValid
 * Signature: ()Lbwapi4/WalkPosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_WalkPosition_makeValid
  (JNIEnv *, jobject);

/*
 * Class:     bwapi4_WalkPosition
 * Method:    getApproxDistance
 * Signature: (Lbwapi4/WalkPosition;)I
 */
JNIEXPORT jint JNICALL Java_bwapi4_WalkPosition_getApproxDistance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bwapi4_WalkPosition
 * Method:    getLength
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_bwapi4_WalkPosition_getLength
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
