/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Utils */

#ifndef _Included_bwapi4_Utils
#define _Included_bwapi4_Utils
#ifdef __cplusplus
extern "C" {
#endif
#undef bwapi4_Utils_Previous
#define bwapi4_Utils_Previous 1L
#undef bwapi4_Utils_Cyan
#define bwapi4_Utils_Cyan 2L
#undef bwapi4_Utils_Yellow
#define bwapi4_Utils_Yellow 3L
#undef bwapi4_Utils_White
#define bwapi4_Utils_White 4L
#undef bwapi4_Utils_Grey
#define bwapi4_Utils_Grey 5L
#undef bwapi4_Utils_Red
#define bwapi4_Utils_Red 6L
#undef bwapi4_Utils_Green
#define bwapi4_Utils_Green 7L
#undef bwapi4_Utils_Red_P1
#define bwapi4_Utils_Red_P1 8L
#undef bwapi4_Utils_Tab
#define bwapi4_Utils_Tab 9L
#undef bwapi4_Utils_Newline
#define bwapi4_Utils_Newline 10L
#undef bwapi4_Utils_Invisible_no_override
#define bwapi4_Utils_Invisible_no_override 11L
#undef bwapi4_Utils_Remove_beyond
#define bwapi4_Utils_Remove_beyond 12L
#undef bwapi4_Utils_Clear_formatting
#define bwapi4_Utils_Clear_formatting 13L
#undef bwapi4_Utils_Blue
#define bwapi4_Utils_Blue 14L
#undef bwapi4_Utils_Teal
#define bwapi4_Utils_Teal 15L
#undef bwapi4_Utils_Purple
#define bwapi4_Utils_Purple 16L
#undef bwapi4_Utils_Orange
#define bwapi4_Utils_Orange 17L
#undef bwapi4_Utils_Right_Align
#define bwapi4_Utils_Right_Align 18L
#undef bwapi4_Utils_Center_Align
#define bwapi4_Utils_Center_Align 19L
#undef bwapi4_Utils_Invisible
#define bwapi4_Utils_Invisible 20L
#undef bwapi4_Utils_Brown
#define bwapi4_Utils_Brown 21L
#undef bwapi4_Utils_White_p7
#define bwapi4_Utils_White_p7 22L
#undef bwapi4_Utils_Yellow_p8
#define bwapi4_Utils_Yellow_p8 23L
#undef bwapi4_Utils_Green_p9
#define bwapi4_Utils_Green_p9 24L
#undef bwapi4_Utils_Brighter_Yellow
#define bwapi4_Utils_Brighter_Yellow 25L
#undef bwapi4_Utils_Cyan_default
#define bwapi4_Utils_Cyan_default 26L
#undef bwapi4_Utils_Pinkish
#define bwapi4_Utils_Pinkish 27L
#undef bwapi4_Utils_Dark_Cyan
#define bwapi4_Utils_Dark_Cyan 28L
#undef bwapi4_Utils_Greygreen
#define bwapi4_Utils_Greygreen 29L
#undef bwapi4_Utils_Bluegrey
#define bwapi4_Utils_Bluegrey 30L
#undef bwapi4_Utils_Turquoise
#define bwapi4_Utils_Turquoise 31L
#ifdef __cplusplus
}
#endif
#endif
