/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_PositionOrUnit */

#ifndef _Included_bwapi_PositionOrUnit
#define _Included_bwapi_PositionOrUnit
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
