/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_UnitSizeType */

#ifndef _Included_bwapi_UnitSizeType
#define _Included_bwapi_UnitSizeType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_UnitSizeType
 * Method:    toString_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi_UnitSizeType_toString_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
