/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi4_Event */

#ifndef _Included_bwapi4_Event
#define _Included_bwapi4_Event
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi4_Event
 * Method:    getPosition_native
 * Signature: (J)Lbwapi4/Position;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Event_getPosition_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Event
 * Method:    getText_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bwapi4_Event_getText_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Event
 * Method:    getUnit_native
 * Signature: (J)Lbwapi4/Unit;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Event_getUnit_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Event
 * Method:    getPlayer_native
 * Signature: (J)Lbwapi4/Player;
 */
JNIEXPORT jobject JNICALL Java_bwapi4_Event_getPlayer_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwapi4_Event
 * Method:    isWinner_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi4_Event_isWinner_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
