/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwapi_TilePosition */

#ifndef _Included_bwapi_TilePosition
#define _Included_bwapi_TilePosition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwapi_TilePosition
 * Method:    isValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_bwapi_TilePosition_isValid
  (JNIEnv *, jobject);

/*
 * Class:     bwapi_TilePosition
 * Method:    makeValid
 * Signature: ()Lbwapi/TilePosition;
 */
JNIEXPORT jobject JNICALL Java_bwapi_TilePosition_makeValid
  (JNIEnv *, jobject);

/*
 * Class:     bwapi_TilePosition
 * Method:    getLength
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_bwapi_TilePosition_getLength
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
