/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwta_Chokepoint */

#ifndef _Included_bwta_Chokepoint
#define _Included_bwta_Chokepoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwta_Chokepoint
 * Method:    getRegions_native
 * Signature: (J)Lbwapi/Pair;
 */
JNIEXPORT jobject JNICALL Java_bwta_Chokepoint_getRegions_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Chokepoint
 * Method:    getSides_native
 * Signature: (J)Lbwapi/Pair;
 */
JNIEXPORT jobject JNICALL Java_bwta_Chokepoint_getSides_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Chokepoint
 * Method:    getCenter_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwta_Chokepoint_getCenter_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Chokepoint
 * Method:    getWidth_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwta_Chokepoint_getWidth_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
