/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bwta_Polygon */

#ifndef _Included_bwta_Polygon
#define _Included_bwta_Polygon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bwta_Polygon
 * Method:    getArea_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwta_Polygon_getArea_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Polygon
 * Method:    getPerimeter_native
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bwta_Polygon_getPerimeter_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Polygon
 * Method:    getCenter_native
 * Signature: (J)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwta_Polygon_getCenter_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Polygon
 * Method:    isInside_native
 * Signature: (JLbwapi/Position;)Z
 */
JNIEXPORT jboolean JNICALL Java_bwta_Polygon_isInside_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwta_Polygon
 * Method:    getNearestPoint_native
 * Signature: (JLbwapi/Position;)Lbwapi/Position;
 */
JNIEXPORT jobject JNICALL Java_bwta_Polygon_getNearestPoint_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     bwta_Polygon
 * Method:    getHoles_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwta_Polygon_getHoles_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bwta_Polygon
 * Method:    getPoints_native
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_bwta_Polygon_getPoints_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
